name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run pipeline
        run: |
          python src/prepare_data.py
          python src/validate.py
          python src/make_map.py
      - name: Upload map artifact
        uses: actions/upload-artifact@v4
        with:
          name: rembc_map
          path: docs/rembc_map.html
